pool:
  name: Hosted VS2017

steps:
- task: PowerShell@2
  displayName: 'Install dependencies'
  inputs:
    targetType: filePath
    filePath: './Install-Dependencies.ps1'

- task: PowerShell@2
  displayName: 'Build image'
  inputs:
    targetType: filePath
    filePath: './Build-Image.ps1'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    ArtifactName: 'drop'

